apiVersion: v1
kind: Service
metadata:
  name: {{ include "hexxit.fullname" . }}
  labels:
    {{- include "hexxit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: {{ .Values.service.protocol}}
      name: port1
  selector:
    {{- include "hexxit.selectorLabels" . | nindent 4 }}
    app: hexxit

