apiVersion: v1
kind: Service
metadata:
  name: {{ include "bedrock.fullname" . }}
  labels:
    {{- include "bedrock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: {{ .Values.service.protocol}}
  selector:
    {{- include "bedrock.selectorLabels" . | nindent 4 }}
    app: normal
