apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
    AUTHKEY:  {{ .Values.AUTHKEY | b64enc }}
    GAMEMODE: {{ .Values.GAMEMODE | b64enc }}
    MAP: {{ .Values.MAP | b64enc }}
    WORKSHOP: {{ .Values.WORKSHOP | b64enc }}
    WORKSHOPDL: {{ .Values.WORKSHOPDL | b64enc }}