apiVersion: v1
kind: Service
metadata:
  name: {{ include "garrysmod.fullname" . }}
  labels:
    {{- include "garrysmod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: {{ .Values.service.protocol1 }}
      name: port1
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: {{ .Values.service.protocol2 }}
      name: port2
  selector:
    {{- include "garrysmod.selectorLabels" . | nindent 4 }}





