apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  RCON_PASSWORD: {{ .Values.RCON_PASSWORD | b64enc }}
  ADMIN_PASSWORD: {{ .Values.ADMIN_PASSWORD | b64enc }}
  SERVER_PASSWORD: {{ .Values.SERVER_PASSWORD | b64enc }}
  SERVER_PUBLIC_NAME: {{ .Values.SERVER_PUBLIC_NAME | b64enc }}
  SERVER_PUBLIC_DESC: {{ .Values.SERVER_PUBLIC_DESC | b64enc }}
  RCON_PORT: {{ .Values.RCON_PORT | b64enc }}
  XMX: {{ .Values.XMX | b64enc }}
  XMS: {{ .Values.RCON_PASSWORD | b64enc }}
  SERVER_NAME: {{ .Values.SERVER_NAME | b64enc }}