apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectzomboid.fullname" . }}
  labels:
    {{- include "projectzomboid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      targetPort: {{ .Values.service.port1 }}
      protocol: {{ .Values.service.protocol }}
      name: port1
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: {{ .Values.service.protocol }}
      name: port2
    - port: {{ .Values.service.port3 }}
      targetPort: {{ .Values.service.port3 }}
      protocol: {{ .Values.service.protocol }}
      name: port3
  selector:
    {{- include "projectzomboid.selectorLabels" . | nindent 4 }}
